plugin:
    name: 'acte.passwordpolicy::lang.plugin.name'
    description: 'acte.passwordpolicy::lang.plugin.description'
    author: 'Acte Solutions'
    icon: oc-icon-lock
    homepage: 'https://www.acte-solutions.com'
permissions:
    acte.passwordpolicy.manage_policies:
        tab: 'acte.passwordpolicy::lang.plugin.name'
        label: 'acte.passwordpolicy::lang.plugin.name'
